# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PolygonToPoint_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PolygonToPointDialogBase(object):
    def setupUi(self, PolygonToPointDialogBase):
        PolygonToPointDialogBase.setObjectName("PolygonToPointDialogBase")
        PolygonToPointDialogBase.resize(340, 276)
        self.layerComboBox = QtWidgets.QComboBox(PolygonToPointDialogBase)
        self.layerComboBox.setGeometry(QtCore.QRect(10, 30, 321, 32))
        self.layerComboBox.setObjectName("layerComboBox")
        self.fieldComboBox = QtWidgets.QComboBox(PolygonToPointDialogBase)
        self.fieldComboBox.setGeometry(QtCore.QRect(10, 90, 321, 32))
        self.fieldComboBox.setObjectName("fieldComboBox")
        self.newFieldNameLine = QtWidgets.QLineEdit(PolygonToPointDialogBase)
        self.newFieldNameLine.setGeometry(QtCore.QRect(20, 150, 301, 21))
        self.newFieldNameLine.setObjectName("newFieldNameLine")
        self.radioGpkg = QtWidgets.QRadioButton(PolygonToPointDialogBase)
        self.radioGpkg.setGeometry(QtCore.QRect(20, 190, 99, 20))
        self.radioGpkg.setObjectName("radioGpkg")
        self.radioShp = QtWidgets.QRadioButton(PolygonToPointDialogBase)
        self.radioShp.setGeometry(QtCore.QRect(130, 190, 99, 20))
        self.radioShp.setObjectName("radioShp")
        self.runButton = QtWidgets.QPushButton(PolygonToPointDialogBase)
        self.runButton.setGeometry(QtCore.QRect(110, 230, 113, 32))
        self.runButton.setObjectName("runButton")
        self.label = QtWidgets.QLabel(PolygonToPointDialogBase)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PolygonToPointDialogBase)
        self.label_2.setGeometry(QtCore.QRect(19, 70, 191, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(PolygonToPointDialogBase)
        self.label_3.setGeometry(QtCore.QRect(19, 130, 141, 20))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(PolygonToPointDialogBase)
        QtCore.QMetaObject.connectSlotsByName(PolygonToPointDialogBase)

    def retranslateUi(self, PolygonToPointDialogBase):
        _translate = QtCore.QCoreApplication.translate
        PolygonToPointDialogBase.setWindowTitle(_translate("PolygonToPointDialogBase", "Polygon to Point"))
        self.radioGpkg.setText(_translate("PolygonToPointDialogBase", "gpkg"))
        self.radioShp.setText(_translate("PolygonToPointDialogBase", "shp"))
        self.runButton.setText(_translate("PolygonToPointDialogBase", "Run"))
        self.label.setText(_translate("PolygonToPointDialogBase", "เลือกเลเยอร์ Polygon"))
        self.label_2.setText(_translate("PolygonToPointDialogBase", "เลือกฟิลด์ที่ต้องการเก็บไปไฟล์ใหม่"))
        self.label_3.setText(_translate("PolygonToPointDialogBase", "ชื่อคอลัมน์ใหม่"))
